name: Display differences between ".env.enc" files
description: |
  This annotates the current pull request with differences between the ".env.enc" files in the base and head branches.
  It output the key names that have been added, removed, and modified on the head branch, 
  both as a job summary and as a comment on the branch.

on:
  pull_request:
    paths:
      - '.env.enc'

jobs:
  get-file-differences:
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.produce-diff.outputs.message }}
    steps:
      - name: Checkout head branch
        uses: actions/checkout@v4

      - run: mkdir base

      - name: Checkout file from base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
          path: base
          sparse-checkout-cone-mode: false
          submodules: true
          sparse-checkout: |
            .env.enc

      - run: npm ci

#      # This is assuming a generic decryption script;
#      # Replace the command with your own decryption script!
#      - name: Decrypt current (head) ref file as "updated"
#        run: npm run decrypt
#
#      # This is assuming a generic decryption script;
#      # Replace the command with your own decryption script!
#      - name: Decrypt base (target) ref file as "original"
#        run: cd base && npm run decrypt

      - run: npm run diff-env-files
        id: produce-diff
        env:
          BASE_FILE_PATH: ./base/.env
          CURRENT_FILE_PATH: ./.env
          DOTENVENC_PASS: ${{ secrets.ENV_ENC_DECRYPTION_KEY }}

  post-or-edit-comment:
    runs-on: ubuntu-latest
    needs: [ get-file-differences ]
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'Updates to ".env" file in this pull request'

      - name: Add or replace comment with newest file differences
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            # Updates to ".env" file in this pull request

            ${{ needs.get-file-differences.outputs.message  }}
          edit-mode: replace
